modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="lively_danmaku"
version="${mod_version}"
displayName="lively_danmaku"
authors="Crystal1921"
logoFile="logo.png"
credits = "TartaricAcid,ZUN"
description='''
This is crystal1921, the 1.20.1 Modding tutorial mod.
我很可爱，请给我钱，给我star
https://github.com/Crystal1921
材质协力：Da_black大黑, LibeccioEA 西南风
'''