modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="crystal"
version="${mod_version}"
displayName="crystal"
authors="crystal1921"
logoFile="crystal_logo.jpg"
description='''
This is crystal1921, the 1.19.4 Modding tutorial example mod.
我很可爱，请给我钱，给我star
https://github.com/Crystal1921
'''