modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="lively_danmaku"
version="${mod_version}"
displayName="lively_danmaku"
authors="crystal1921"
logoFile="crystal_logo.jpg"
description='''
This is crystal1921, the 1.20.1 Modding tutorial mod.
我很可爱，请给我钱，给我star
https://github.com/lively_danmaku1921
材质协力：Big_black大黑, LibeccioEA 西南风
'''